### ISSUE TITLE
Spelling error in site configuration variable "forwardRedirectParamters"

### ISSUE THREAD

**Issue by twllndr** [lochmueller/language_detection#1]
Just from looking at the screenshot in your README.md I saw a spelling error in the variable "forwardRedirectParamters" - should be "forwardRedirectParameters" I think.

https://github.com/lochmueller/language_detection/blob/fd31b1bf78c48a346f9cda778a05ca03fe9353ee/Configuration/SiteConfiguration/Overrides/sites.php#L50

**Comment by lochmueller** [comment]
Thanks @twllndr for the incredible fast feedback. Fixed in master and next release.
