### ISSUE TITLE
 $needle can not be interpreted as string or has zero length

### ISSUE THREAD

**Issue by michelrojahn** [lochmueller/language_detection#11]
After installation i got the following error when i click a navigationpoint in frontend:

[CRITICAL] request="fcc19ae5fb0be" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1347135547: $needle can not be interpreted as string or has zero length | InvalidArgumentException thrown in file /html/typo3/typo3_src-10.4.9/typo3/sysext/core/Classes/Utility/StringUtility.php in line 42.

**Comment by lochmueller** [comment]
Hey @michelrojahn ,

Could you check the FromCurrentPageListener function, why the base of the site configuration is empty in your case?! This should be a full URL: https://github.com/lochmueller/language_detection/blob/master/Classes/Check/FromCurrentPageListener.php#L17

Do you "incomplete URIs" (just the path oder "/") in your site configuration as base? ( https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/BaseVariants.html )

Regards,
Tim

**Comment by michelrojahn** [comment]
Hey Tim,

thanks for your quick reply. You're right. The normal Entrypoint was "/" an the correct URL was set in language settings. I changed it. The normal entrypoint ist now the fully qualified domain and in the default language now i have "/". With these setting your extension work as expected. Thank you and have a nice day.

With kind regards from Porta Westfalica,
Michel

**Comment by lochmueller** [comment]
Hey @michelrojahn ,
fixed in current master. A base URI of "/" is allowed https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/Basics.html#base and the extension should not break :) Will also release a new version.
Regards,
Tim
