### ISSUE TITLE
Migrate TCA for TYPO3 11.2

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/language_detection#12]
Avoid Exception `Unknown special value languages for field fallbackDetectionLanguage of table site`. Problem would be, that  migration: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-57082-NewTCATypeLanguage.html

**Comment by aiturria-spain** [comment]
Hi Tim

Thanks a lot for fixing the problem..

Kind regards
