### ISSUE TITLE
Dropdown "Fallback detection language" is empty

### ISSUE THREAD

**Issue by aiturria-spain** [lochmueller/language_detection#13]
The dropdown to set the fallback language is empty. The defined site languages are not displayed.
![language_detection](https://user-images.githubusercontent.com/62375823/120981217-ba908080-c777-11eb-8f8c-efab3a44cc32.jpg)

**Comment by lochmueller** [comment]
Hey @aiturria-spain
fixed in current master and next release.
Regards,
Tim
