### ISSUE TITLE
Detect language on sub-pages 

### ISSUE THREAD

**Issue by cepheiVV** [lochmueller/language_detection#15]
The language detection works when opening the URL somedomain.org
When opening a subpage, e.g. somedomain.org/some/page the language detection doesn't seem to do anything.

Tested with TYPO3 10.4.20 and language_detection 1.7.1

**Comment by lochmueller** [comment]
Hey @cepheiVV 
This is right. This check the PathListener: https://github.com/lochmueller/language_detection/blob/master/Classes/Check/PathListener.php
Which is the value of "allowAllPaths" in your configuration. If you set this to "" this should work?!?!

Regards,
Tim

**Comment by cepheiVV** [comment]
I haven't changed it after installing the extension.
This setting was on `allowAllPaths: false` 

Works now on subpages, but the redirect brings me to the home page.

Request: somedomain.org/test
FR detected, redirects to somedomain.org/fr

**Comment by lochmueller** [comment]
You are right. EXT:language_dection is a Middleware in front of the TSFE and concepts like pages. So I think this is not so easy possible. I will check this for the future.

**Comment by lochmueller** [comment]
Keep in mind: I don't know if it useful to use the language detection on every side of the webpage. A user who found a page by e.g. google found the page in the language he searched for. So it is not useful to redirect this use to another page?!

**Comment by alsodenn** [comment]
From a marketing point of view, this makes perfect sense. You can communicate a short URL for a landing page without a language part URL and the user is automatically directed to the correct language. 
This can make a lot of sense for all kinds of landing pages.
