### ISSUE TITLE
Typo in WorkspacePreviewListener

### ISSUE THREAD

**Issue by mat-hew1** [lochmueller/language_detection#16]
In a current version 1.8.0 is in Classes/Check/WorkspacePreviewListener.php on line 14: `\in_array('ADMCMD_previewWS', $argumentsNames)`, but $argumentsNames is not defined anyway. It's a code piece from an older version.

**Comment by lochmueller** [comment]
You are right... wrong fix from rector cleanups. I will push a bugfix version in a few minutes.

**Comment by mat-hew1** [comment]
Good job, thanks. Was really :fire: fix :+1:
