### ISSUE TITLE
use the detection result in typoscript

### ISSUE THREAD

**Issue by mxsteini** [lochmueller/language_detection#28]
Hi is there a way to use the detection result in typoscript?
I need some condition to the original detected country (en-uk vs en-us) to give the customer the correct contact.

**Comment by lochmueller** [comment]
Hey @mxsteini 

nice idea, but keep in mind, that Client based conditions in TS are not cachable and your page performance will be much slower. In general, you could create a custom TypoScript condition ( https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/SymfonyExpressionLanguage/Index.html#sel-within-typoscript-conditions ) and call the LanguageDetectionHandler ( https://github.com/lochmueller/language_detection/blob/main/Classes/Handler/LanguageDetectionHandler.php ) with the current server request.  (not tested, but this could be the basic structure).

Other option is, that you use separated languages for en-uk and en-us (inkl. language fallback). Then the editor can control the content itself. Last option could be a AJAX request. You can call '/language.json' to get the current user preferences/languages and control the content based on this information.

Regards,
Tim

**Comment by mxsteini** [comment]
Sounds good.
Thanks for the fast reply.
