### ISSUE TITLE
Browser language detection breaks when used along with EXT:staticfilecache

### ISSUE THREAD

**Issue by SruthiKumar333** [lochmueller/language_detection#29]
Hi,
I am using EXT: language_detection along with  EXT:staticfilecache. Actually both the extensions are working fine on their own, but when staticfilecache is enabled,  the browser language detection feature breaks. 

For example, my browser language is English. So my website https://example.com should redirect to https://example.com/en/. But as https://example.com Is already cached, the default language is rendered right away.

Please suggest a possible workaround.

**Comment by lochmueller** [comment]
No feedback... please choose one of the 3 options. Closed.
