### ISSUE TITLE
Issues with other extensions like sf_register

### ISSUE THREAD

**Issue by SMA-cgn** [lochmueller/language_detection#31]
Hi, when enabling language detection then urls to confirm a new front end user (eg generated and sent as email link by sf_register) do not work anymore.
To be more precise. Clicking the link in the email does not do the job anymore eg to confirm a registration.
Pasting the link url directly in the browser still works.

Do you have any recommendation how to handle that?

Thanks a lot!

**Comment by lochmueller** [comment]
Hey @SMA-cgn 

There is only one place, that change the rendering. These are the two middlewares:
https://github.com/lochmueller/language_detection/blob/main/Configuration/RequestMiddlewares.php

BUT.... JSON Handler works only on one URI ('/language.json')...
https://github.com/lochmueller/language_detection/blob/main/Classes/Handler/JsonDetectionHandler.php
... and Language Detection Handler only if all four events are valid...
https://github.com/lochmueller/language_detection/blob/main/Classes/Handler/LanguageDetectionHandler.php
... but on a deeplink the base check should be disabled: isLanguageDetectionEnable

Or do you use the option "allowAllPaths"? It is recommended not using this option!!! If you using allowAllPaths, perhaps you can add the parameters to forward.redirect.parameter.

Please send use more debugging information (HTTP headers, redirect status, URI example etc.)

Regards,
Tim

**Comment by SMA-cgn** [comment]
Hi Tim,
thanks for your reply. So strange, however it works as expected today.
I have spend so much time on testing yesterday  8)     I am happy that it works now & give it some more tries. 
Your extension is great!

Thanks, Steffen

**Comment by lochmueller** [comment]
OK @SMA-cgn 
so I will close this issue. If the problem reappear, please open a new ticket with more debug information.
Regards,
Tim
