### ISSUE TITLE
MaxMind integration does not allow to override user language like GeoPluginDetect

### ISSUE THREAD

**Issue by websi** [lochmueller/language_detection#33]
The MaxMind detect implementation does not allow to prepend or replace the user language from the browser.

https://github.com/lochmueller/language_detection/blob/99577353cf99b0bff3504322e32852b59b6c3436/Classes/Detect/MaxMindDetect.php#L46

The third parameter of "addLocaleByMode" is not used.

**Comment by plaemmer** [comment]
Hi @lochmueller ,

would it be possible to integrate the fix into version 3.0.1 as well? I have the problem that we bought a paid MaxMind license, but unfortunately the option doesn't work. We have stored the ID and the key in the SiteConfigs. Update to V11 is not possible at the moment.

Regards,
Philipp

**Comment by lochmueller** [comment]
Hey @plaemmer ,
sorry, but I do not release old versions except, there are critical security fixes.
If you are in composer mode, you can use `cweagans/composer-patches` and patch the changes (perhaps directly with the patches from github via URL).

Regards,
Tim
