### ISSUE TITLE
Only works for the root page

### ISSUE THREAD

**Issue by liayn** [lochmueller/language_detection#4]
Please clarify this straight in the readme and the ext description. Saves hours of searching, why no redirect happens on deep links.

**Comment by lochmueller** [comment]
Hey @liayn 
thanks... could be possible, but online with referrer check (already part of the extension https://github.com/lochmueller/language_detection/blob/master/Classes/Check/FromCurrentPageListener.php ) or language cookie (currently not part of the extension), right? Or do you have a bulletproof concept for deeplinks?

This is the check for the detection path: https://github.com/lochmueller/language_detection/blob/master/Classes/Check/PathListener.php We can add a option to ignore this check and add a second option to set a language cookie?!

Regards,
Tim

**Comment by liayn** [comment]
I actually came from https://extensions.typo3.org/extension/site_language_redirection/, which uses a cookie based solution.
It worked okay for us until I realized today that it does not preserve GET parameters, hence new detail pages are not auto-redirected properly if hit the first time. A PR is pending since August...

I tried your ext then and was wondering a long time, why no redirect is issued at all until I inspected the code in detail finding the PathListener.
So yes, either approach is okay for me (root only or every page), but it should be documented clearly and as a first information.

**Comment by lochmueller** [comment]
You are right. I will add the "root only or every page"-option and will add some more documentation about the default Listener of the four events to the README.md file.

Thanks for the hint.

**Comment by liayn** [comment]
"Every page" should of course include the GET parameters, otherwise it is pretty useless. (as with site_language_redirection now)

**Comment by lochmueller** [comment]
Yes. This is already part of the extension. The default Response object add the configured GET params to the target URI: https://github.com/lochmueller/language_detection/blob/master/Classes/Response/DefaultResponse.php#L42 Do you mean this option?

**Comment by liayn** [comment]
yes, right. manual config is okay IMO.

**Comment by lochmueller** [comment]
Hey @liayn 
I add some more documentation. Feel free to create new issues in case of missing functions or features.
Regards,
Tim
