### ISSUE TITLE
Adjust xliff to be crowdin compatible and register the extension

### ISSUE THREAD

**Issue by liayn** [lochmueller/language_detection#7]
See https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.html

**Comment by lochmueller** [comment]
Hey @liayn 
The localization team is informed via Slack. As soon the project exists, I will connect this to my Git repository.
Regards,
Tim

**Comment by lochmueller** [comment]
Done. Extension is moved to CrowdIn: https://crowdin.com/project/typo3-extension-languagedetect
