### ISSUE TITLE
Resources/Private missing in composer installation

### ISSUE THREAD

**Issue by peterkraume** [lochmueller/language_detection#8]
When you install the extension via `composer req lochmueller/language-detection`, the folder `Resources/Private` is missing after the installation. The folder is also missing in the zip files of the release.

If you install the extension via `composer req lochmueller/language-detection --prefer-source`, the folder `Resources/Private` is present after installation.

**Comment by lochmueller** [comment]
Hey @peterkraume ,
good point. Fixed in the commit a few seconds ago.
Regards,
Tim
