### ISSUE TITLE
geoplugin.net unavailabe

### ISSUE THREAD

**Issue by peterkraume** [lochmueller/language_detection#9]
The domain geoplugin.net is unavailable, there isn't even a nameserver entry for the domain:

```
; <<>> DiG 9.10.6 <<>> NS geoplugin.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34244
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;geoplugin.net.			IN	NS
```

**Comment by lochmueller** [comment]
That is strange. On my side this service is still working: http://www.geoplugin.net/php.gp?ip=MY-IP-HERE

Do you have a good alternative?

**Comment by peterkraume** [comment]
Sorry, my bad. The domain geoplugin.net was blocked by my local Pi-hole.

**Comment by akroii** [comment]
Reopen because: geoplugin is now subject to a fee
https://www.geoplugin.com/subscription

**Comment by lochmueller** [comment]
Hey @akroii 
it is already replaced in the current version: https://github.com/lochmueller/language_detection/commit/a0abf8980f833f245ae86bf12a0c679905dfd9ad
Regards,
Tim
